### ISSUE TITLE
pipe 到 cowsay 出现乱码

### ISSUE THREAD

**Issue by loggerhead** [egoist/saikou-cli#1]
单独用的时候正常，但是和 cowsay 一起使用就出现乱码，如下图：

![QQ20160202-0@2x.png](https://ooo.0o0.ooo/2016/02/02/56b0a1deca38d.png)
# 环境
- OS X 10.10.5
- iTerm2 Build 2.1.4
- zsh 5.2 (x86_64-apple-darwin14.5.0)
- cowsay 3.02

**Comment by loggerhead** [comment]
~~呃。。这应该是 cowsay 的问题，又提交错了 issue，sorry。~~
直接输入没问题，是不是用了改颜色的符号导致的？

![1.png](https://ooo.0o0.ooo/2016/02/02/56b0abd3d07f1.png)

**Comment by egoist** [comment]
boring 是什么？

**Comment by loggerhead** [comment]
zsh 函数，随机选择一个 cowfile

``` zsh
boring() {
    if [[ $((${RANDOM} % 2)) -eq 0 ]]; then
        CMD=cowsay
    else
        CMD=cowthink
    fi
    FMTS=($($CMD -l | tail -n +2 | xargs))
    RAND=$((${RANDOM} % ${#FMTS[@]} + 1))
    saikou | $CMD -f ${FMTS[$RAND]}
}
```

**Comment by egoist** [comment]
这个应该是偶尔产生，暂时不知道什么原因。。

**Comment by loggerhead** [comment]
应该是换行就会产生，可能是产生颜色的转义字符导致的，添加一个 option 关掉颜色我再试试？

**Comment by egoist** [comment]
ok, 重新 install 一下，`saikou --no-color`

**Comment by loggerhead** [comment]
ok，bug 没了

![1.png](https://ooo.0o0.ooo/2016/02/02/56b0c448a6710.png)

**Comment by egoist** [comment]
233 😂

**Comment by loggerhead** [comment]
目测 cowsay 一行只能 13 个中文，你可以每个字符加一对颜色转义与重置，或者每 13 个中文字符加一对

**Comment by egoist** [comment]
这是个办法，我明天试试👍🏻

**Comment by loggerhead** [comment]
Good night : )

**Comment by likeqc** [comment]
我也遇到了这个问题，然后碰巧在`~/.zshrc`指定编码后正常了
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
